export { default as Home} from './Home/Home'
export { default as GettingStarted} from './GettingStarted/GettingStarted'
export { default as Examples} from './Examples/Examples'
export { default as Docs} from './Docs/Docs'
export { default as LogIn} from './LogIn/LogIn'